#include "i2s_mic_std.h"

I2S_Mic::I2S_Mic(i2s_port_t i2s_num, uint32_t sample_rate)
{
  m_i2s_num = i2s_num;
  m_sample_rate = sample_rate;

  m_gain = 1.0;

 /* Get the default channel configuration by helper macro.
  * This helper macro is defined in `i2s_common.h` and shared by all the I2S communication modes.
  * It can help to specify the I2S role and port ID */
  m_chan_cfg = I2S_CHANNEL_DEFAULT_CONFIG(I2S_NUM_AUTO, I2S_ROLE_MASTER);

  /* Allocate a new RX channel and get the handle of this channel */
  i2s_new_channel(&m_chan_cfg, NULL, &rx_handle);

  /* Setting the configurations, the slot configuration and clock configuration can be generated by the macros
   * These two helper macros are defined in `i2s_std.h` which can only be used in STD mode.
   * They can help to specify the slot and clock configurations for initialization or updating */
  m_i2s_std_cfg = {
    .clk_cfg = I2S_STD_CLK_DEFAULT_CONFIG(sample_rate),
    .slot_cfg = I2S_STD_MSB_SLOT_DEFAULT_CONFIG(I2S_DATA_BIT_WIDTH_32BIT, I2S_SLOT_MODE_MONO),
    .gpio_cfg = {
      .mclk = I2S_GPIO_UNUSED,
      .bclk = I2S_GPIO_UNUSED,
      .ws = I2S_GPIO_UNUSED,
      .dout = I2S_GPIO_UNUSED,
      .din = I2S_GPIO_UNUSED,
      .invert_flags = {
        .mclk_inv = false,
        .bclk_inv = false,
        .ws_inv = false
      }
    }
  };
}

void I2S_Mic::begin() 
{
  /*
  i2s_driver_install(m_i2s_num, &m_i2s_config, 0, NULL);
  i2s_set_pin(m_i2s_num, &m_i2s_pin_config);
  i2s_set_clk(m_i2s_num, m_sample_rate, I2S_BITS_PER_SAMPLE_32BIT, I2S_CHANNEL_MONO);
  */
  /* Initialize the channel */
  i2s_channel_init_std_mode(rx_handle, &m_i2s_std_cfg);

  /* Before reading data, start the RX channel first */
  i2s_channel_enable(rx_handle);
}

void I2S_Mic::end()
{
  //i2s_driver_uninstall(m_i2s_num); //stop & destroy i2s driver
  /* Have to stop the channel before deleting it */
  i2s_channel_disable(rx_handle);
  /* If the handle is not needed any more, delete it to release the channel resources */
  i2s_del_channel(rx_handle);
}

void I2S_Mic::setPinout(uint8_t bck, uint8_t ws, uint8_t data_in)
{
  m_i2s_std_cfg.gpio_cfg.mclk = I2S_GPIO_UNUSED,
  m_i2s_std_cfg.gpio_cfg.bclk =  (gpio_num_t)bck;
  m_i2s_std_cfg.gpio_cfg.ws = (gpio_num_t)ws;
  m_i2s_std_cfg.gpio_cfg.dout = I2S_GPIO_UNUSED,
  m_i2s_std_cfg.gpio_cfg.din = (gpio_num_t)data_in;
}

void I2S_Mic::setGain(float gain)
{
  m_gain = gain;
}

void I2S_Mic::read(void *dest, size_t size, size_t *bytes_read, uint32_t timeout_ms)
{
  // uint32_t timeout_ms
  i2s_channel_read(rx_handle, dest, size, bytes_read, timeout_ms);
}

void I2S_Mic::read16bits(int16_t *dest, size_t size, size_t *bytes_read, uint32_t timeout_ms)
{
  size_t samples_size = size / sizeof(int16_t);
  
  int32_t i2sBuffer[samples_size];
  
  size_t bytes_read_internal;
  
  //i2s_read(m_i2s_num, (void *)i2sBuffer, samples_size * sizeof(int32_t), &bytes_read_internal, ticks_to_wait);
  i2s_channel_read(rx_handle, (void *)i2sBuffer, samples_size * sizeof(int32_t), &bytes_read_internal, timeout_ms);
  
  // Store the number of samples that have been read.
  int samples_read = bytes_read_internal / sizeof(int32_t);
  
  for (int x = 0; x < samples_read; x++) {
    dest[x] = (i2sBuffer[x] >> 16) * m_gain;
  }

  // Compute the bytes read as int16_t.
  *bytes_read = (size_t)samples_read * sizeof(int16_t);
}
